name: trollzor's CyberSec blog 
title: trollzor's CyberSec blog
description: You'll find here mainly writeups of various HackTheBox boxes/challenges and rarely CTF challenges solves.

tags:
  - blog
  - hackthebox
  - writeups
  - ctf

show_hero: false
paginate: 10

menu:
  - title: Home
    url: /
  - title: About
    url: /about

email: trollzorhacks@gmail.com
disqus_username: disqus_46qhhwXwbl
